CREATE USER hr IDENTIFIED BY 0000;
GRANT CONNECT, RESOURCE TO SCOTT;
ALTER USER SCOTT DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER HR ACCOUNT UNLOCK;
ALTER USER SCOTT IDENTIFIED BY tiger;
--계정 잠금해제
ALTER USER hr account unlock;